#!/usr/bin/env node
/**
 * Sync prompts/*.txt + llm-config.json into src/generated/llmPrompts.ts
 * and update devvit.json default monitorSubreddits from config.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const promptsDir = path.join(root, 'prompts');
const outDir = path.join(root, 'src', 'generated');
const outFile = path.join(outDir, 'llmPrompts.ts');
const devvitFile = path.join(root, 'devvit.json');

function readPrompt(name) {
  return fs.readFileSync(path.join(promptsDir, name), 'utf8').trim();
}

function applyWordLimits(text, minWords, maxWords) {
  return text
    .replaceAll('{{MIN_WORDS}}', String(minWords))
    .replaceAll('{{MAX_WORDS}}', String(maxWords));
}

function main() {
  const config = JSON.parse(
    fs.readFileSync(path.join(promptsDir, 'llm-config.json'), 'utf8')
  );

  const { minWords, maxWords } = config.commentDraft;
  const hypericumDomains = readPrompt('hypericum-domains.txt');

  let insightTemplate = readPrompt('insight-extraction.prompt.txt').replace(
    '{{HYPERICUM_DOMAINS}}',
    hypericumDomains
  );

  const commentBriefing = applyWordLimits(
    readPrompt('comment-draft-briefing.txt'),
    minWords,
    maxWords
  );

  fs.mkdirSync(outDir, { recursive: true });

  const source = `// AUTO-GENERATED by scripts/sync-prompts.mjs — do not edit by hand.
// Edit prompts/*.txt or prompts/llm-config.json, then run: npm run sync-prompts

export const LLM_CONFIG = ${JSON.stringify(config, null, 2)} as const;

export type LlmConfig = typeof LLM_CONFIG;

export const DEFAULT_MONITOR_SUBREDDITS = LLM_CONFIG.defaultMonitorSubreddits;

export const HYPERICUM_DOMAIN_CLUSTERS = LLM_CONFIG.hypericumDomainClusters;

export const INSIGHT_INTENT_THRESHOLD = LLM_CONFIG.thresholds.insightIntentScore;

export const DRAFT_INTENT_THRESHOLD = LLM_CONFIG.thresholds.draftIntentScore;

export const COMMENT_DRAFT_MIN_WORDS = LLM_CONFIG.commentDraft.minWords;

export const COMMENT_DRAFT_MAX_WORDS = LLM_CONFIG.commentDraft.maxWords;

export const EXPORT_MIN_DRAFTED_AT_MS = Date.parse(
  LLM_CONFIG.exportMinDraftedAt ?? ''
) || 0;

export const INSIGHT_EXTRACTION_TEMPLATE = ${JSON.stringify(insightTemplate)};

export const COMMENT_DRAFT_BRIEFING = ${JSON.stringify(commentBriefing)};
`;

  fs.writeFileSync(outFile, source, 'utf8');
  console.log(`Wrote ${path.relative(root, outFile)}`);

  const devvit = JSON.parse(fs.readFileSync(devvitFile, 'utf8'));
  const monitorDefault = config.defaultMonitorSubreddits.join(',');
  const monitorSetting = devvit.settings?.subreddit?.monitorSubreddits;
  if (monitorSetting) {
    monitorSetting.defaultValue = monitorDefault;
    fs.writeFileSync(devvitFile, `${JSON.stringify(devvit, null, 2)}\n`, 'utf8');
    console.log(`Updated devvit.json monitorSubreddits default (${config.defaultMonitorSubreddits.length} subs)`);
  }
}

main();
